project:
  type: website
  output-dir: docs

website:
  title: "FPCG Lab"
  navbar:
    background: "#355C7D"
    foreground: white
    search: true
    left:
      - href: index.qmd
        text: " "
        icon: house-door-fill
      - href: about.qmd
        text: PI
      - href: people.qmd
        text: " "
        icon: people-fill
      - href: courses.qmd
        text: Courses
      - href: opportunities.qmd
        text: Opportunities

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

    
    
    